on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files in Directory
        run: ls -la

      - name: Simulate Build Step
        run: echo "No build needed for HTML/CSS"

      - name: Success Message
        run: echo "Workflow completed successfully!"
        
# Triggers on push to main, check out repo, and runs a deploy step 
